# Site settings
title: K7Waterfront.org
organization: K7Waterfront
email: steve@k7Waterfront.org
description: Celebrating and watching the Kingston Ontario waterfront

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://k7waterfront.org" # the base hostname & protocol for your site
twitter_username: k7Waterfront
github_username:  StevenBlack/k7waterfront
site.image_default_alt: "Kingston, Ontario Waterfront"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

exclude: [ "node_modules", "modern-business", "maps", "readme.md", "package.json", "gruntfile.js", "gruntoptions.json", "j.sh",  ]

mapping:
  provider: google_js
  api_key: AIzaSyBRrF26FZMJ-8yWzfhGrZ899_a_EdM56Uk

