# Site settings
title: K7Waterfront.org
email: steve@k7Waterfront.org
description: Celebrating and watching the Kingston Ontario waterfront

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://k7waterfront.org" # the base hostname & protocol for your site
twitter_username: k7Waterfront
github_username:  StevenBlack/k7waterfront

# Build settings
markdown: kramdown
